# Generated by Django 4.2.5 on 2023-10-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='عنوان در URL')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='article-images')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('date', models.DateField(auto_now=True, verbose_name='تاریخ مقاله')),
            ],
            options={
                'verbose_name': ' مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(max_length=500, verbose_name='پیام ')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله مربوطه  ')),
            ],
            options={
                'verbose_name': ' کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='کلاس والد')),
            ],
            options={
                'verbose_name': 'دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(to='article_module.articlecategory', verbose_name='دسته بندی ها '),
        ),
    ]
