# Generated by Django 4.2.5 on 2023-10-06 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='عنوان در URL')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='article-images')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': ' مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('text', models.TextField(verbose_name='متن')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده کامنت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='article_module.articlecomments', verbose_name='والد')),
            ],
            options={
                'verbose_name': ' کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='کلاس والد')),
            ],
            options={
                'verbose_name': 'دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(to='article_module.articlecategory', verbose_name='دسته بندی ها '),
        ),
    ]
