# Generated by Django 4.2.5 on 2023-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_article_options_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
