# Generated by Django 4.2.5 on 2023-10-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_tag_remove_article_tags_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
