# Generated by Django 4.2.5 on 2023-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(max_length=200, verbose_name='email-code verification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='User-avatar', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='mobile-phone'),
        ),
    ]
