# Generated by Django 4.2.5 on 2023-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_user_options_alter_user_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='User-avatar')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatars',
            field=models.ManyToManyField(blank=True, to='user_module.avatar'),
        ),
    ]
