# Generated by Django 4.2.5 on 2023-10-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_avatar_remove_user_avatar_user_avatars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='avatar',
        ),
    ]
