# Generated by Django 4.2.5 on 2023-10-08 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_rename_image_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatars',
        ),
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar gallery '),
        ),
    ]
